permalink: pretty

theme: jekyll_patternbot

collections:
  movies:
    output: true
  checkout:
    output: true
defaults:
  -
    scope:
      path: "_movies"
    values:
      layout: movies
  -
    scope:
      path: "_checkout"
    values:
      layout: checkout


patternbot:
  title: "Cinematorium Today"
  description: |
    Our app allows the user to see and instantaneously buy tickets for the movies that are playing today at the Cinematorium. We want to keep the web app as simple as possible, not being overbearing and disorganized like most cinema websites are. Need something to do today? Check the app for todays showtimes and then drop in and scan the tickets that you've already purchased.
  font_url: "https://fonts.googleapis.com/css?family=Alegreya+Sans:400,700|Overpass:400,700"
  colors:
    background: "--color-dark"
    patterns:
      brand.logos: "--color-neutral"
      icons.icons.icon-slice: "--color-dark"
      sections: "--color-dark"
  rationales:
    colors.primary: |
      That's why we chose this colour. It should be used when...
    colors.secondary: |
      That's why we chose this colour. It should be used when...
    typefaces.primary: |
      That's why we chose this font. It should be used when...
    typefaces.secondary: |
      That's why we chose this font. It should be used when...
