patterns:
  image:
    width:
    fields:
      - name: data
        data:
          source: site.data.movies[1]
          type: "Movie"
  home-card:
    width:
    fields:
      - name: data
        data:
          source: site.data.movies[3]
          type: "Movie"
